# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: portfolio faris
email: mfarix12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
This is Faris Muhaimin portfolio. He will dump every project that he have done in this site
twitter_username: thisisfinx
github_username: f-inx
minimal_mistakes_skin: "dark"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Faris Muhaimin"
  avatar : "https://media-exp1.licdn.com/dms/image/D4E35AQFCEmHdMvAB1w/profile-framedphoto-shrink_200_200/0/1657107509914?e=1660125600&v=beta&t=zIL2YTInwTuzwC5VyAKt-Dhcm1yrit9HwCeLkQh61GM"
  bio    : "This is Faris protfolio. This is the place where Faris dump his projects content as to show that he is in fact not slacking off during uni"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://linktr.ee/thisisfinx"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thisisfinx"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/f-inx"
  

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
  

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
